---
- hosts: application
  tasks:
    - name: Install MySQL and other required packages
      apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
      with_items:
          - python3-pip
          - mysql-client
          - inetutils-ping
          - net-tools
    - name: Prepare app
      copy:
        src: app/    # note the '/' <-- !!!
        dest: /app/
    - name: Installing python requirements for app
      pip:
        requirements: requirements.txt
        chdir: /app