version: '3'

services:
  app:
    image: lab6-agent
    ports:
      - "8080-8090:5000"
  ansible:
    build:
      context: ./ansible
    volumes:
      - ./ansible/inventory:/inventory
      - ./ansible/ansible.cfg:/etc/ansible/ansible.cfg
    depends_on:
      - app