version: '3'

services:
  worker1:
    build:
      context: .
      dockerfile: Dockerfile.worker
      args:
        - WORKER_ID=1
    expose:
      - 80

  worker2:
    build:
      context: .
      dockerfile: Dockerfile.worker
      args:
        - WORKER_ID=2
    expose:
      - 80

  worker3:
    build:
      context: .
      dockerfile: Dockerfile.worker
      args:
        - WORKER_ID=3
    expose:
      - 80

  ansible:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on: 
      - worker1
      - worker2
      - worker3
