---

- name: Setup proxy balancer for remote hosts
  hosts: workers 
  become: true
  vars:
    container_count: 2
    container_name: app
    app_src: /root/work/DevOps/Лабы/Лаб6/ansible/app
    container_location: /home/worker
  tasks:

    - name: copy html file
      copy: src="{{ app_src }}" dest="{{ container_location }}" mode="a+rwx"

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - python3-setuptools
        state: latest
        update_cache: true

    - apt:
        update_cache: yes
        state: latest
        name: python3-pip
    - pip:
        name: docker

    - name: Build App image
      docker_image:
        name: "{{ container_name }}"
        build:
          path: "{{ container_location }}/{{ container_name }}"
        source: build
    - name: Run App container
      docker_container:
         name:  "{{ container_name }}{{ item }}"
         recreate: yes
         restart_policy: unless-stopped
         image:  "{{ container_name }}"
         published_ports:
           - "80{{ item }}0:80{{ item }}0"
         env:
           PORT: "80{{ item }}0"
           WORKER: "{{ item }}"
      with_sequence: count={{ container_count }}
